### PR TITLE
Widen the center column

### PR DESCRIPTION
**Pull request by npmccallum**

### CODE REVIEW

**Comment by npmccallum** [comment]
I know this commit is largely a style preference. However, at 600px width, code blocks could not render 80 columns (actually, far less). I do think this problem needs to be addressed.

**Comment by npmccallum** [comment]
@digitalcraftsman There are now several important changes in this branch. Could you review and merge them?

**Comment by npmccallum** [comment]
@digitalcraftsman This is a friendly reminder to review this branch. :)

**Comment by digitalcraftsman** [comment]
Hello @npmccallum,

thank you very much for submitting this improvements and please excuse the long delay. With multiple exams in a row it can sometimes a bit hard to keep up with all the stuff on GitHub.

Cheers
Digitalcraftsman

**Pull request merged**
